name: Start Helix Runner

on:
  workflow_call:
    inputs:
      yaml_repo:
        description: 'The repository containing the deployment yaml.'
        required: true
        type: string

      deployment_yaml_path:
        description: 'The deployment file path within @yaml_repo.'
        required: false
        type: string
        default: 'deployment.yaml'

      workflow_run_id:
        description: 'The workflow run ID of the calling workflow.'
        required: true
        type: string

jobs:
  print_inputs:
    name: Print Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Yaml Repo
        run: echo ${{ inputs.yaml_repo }}
      - name: Deployment Yaml Path
        run: echo ${{ inputs.deployment_yaml_path }}
      - name: Workflow Run ID
        run: echo ${{ inputs.workflow_run_id }}

  generate_registration_token:
    name: generate_registration_token
    needs: print_inputs
    runs-on: ubuntu-latest
    outputs:
      registration_token: ${{ steps.generate-token.outputs.rt }}
    steps:
      - id: generate-token
        run: |-
          export REGISTRATION_TOKEN=$(curl -X POST -H 'Accept: application/vnd.github+json' -H 'Authorization: token ${{ secrets.GH_PAT }}' https://api.github.com/orgs/HelixBooking/actions/runners/registration-token | jq .token)
          echo $REGISTRATION_TOKEN
          echo "::set-output name=rt::$REGISTRATION_TOKEN"

  start_runner:
    name: Start Helix Runner
    runs-on: ubuntu-latest
    needs: generate_registration_token
    steps:
      - name: Print Inputs
        run: echo ${{ needs.generate_registration_token.outputs.registration_token }}

      - name: 'Authenticate to GKE'
        run: |-
          cd ${HOME}
          echo "${{ secrets.ARTIFACT_REGISTRY_CREDENTIALS }}" | base64 -d > "./gcloud.json"
          gcloud auth activate-service-account --key-file="./gcloud.json"
      - run: |-
          gcloud container clusters get-credentials helix-runners \
          --zone us-central1-c \
          --project ${{ secrets.GCLOUD_PROJECT_ID }}

      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.yaml_repo }}
          ref: main    
          token: ${{ secrets.GH_PAT }}

      - run: |-
          export WORKFLOW_RUN_ID=${{ inputs.workflow_run_id }}
          export REGISTRATION_TOKEN=${{ needs.generate_registration_token.outputs.registration_token }}
          echo $WORKFLOW_RUN_ID
          echo $REGISTRATION_TOKEN
          sed -i -e "s/GH_RUNNER/helix-runner-$WORKFLOW_RUN_ID/" -e "s/GITHUB_REGISTRATION_TOKEN/$REGISTRATION_TOKEN/" ${{ inputs.deployment_yaml_path }}
          cat ${{ inputs.deployment_yaml_path }}
          kubectl config set-context --current --namespace=helix-runners
          kubectl apply -f ${{ inputs.deployment_yaml_path }} -n helix-runners
